// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx28mCx8VSOuUq3FuID2LOgSFiDX34CP4',
    appId: '1:366984975682:web:3239e5b0e16964e13864db',
    messagingSenderId: '366984975682',
    projectId: 'notely-19368',
    authDomain: 'notely-19368.firebaseapp.com',
    storageBucket: 'notely-19368.appspot.com',
    measurementId: 'G-YVZ6YC1FFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBwTXNJ37ZJ4K88C7Yl3UsHKZzr4wnGk8',
    appId: '1:366984975682:android:275144c586b83e533864db',
    messagingSenderId: '366984975682',
    projectId: 'notely-19368',
    storageBucket: 'notely-19368.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5TzexVVBSK-to241nsqPHvcU_-2v1XSA',
    appId: '1:366984975682:ios:65792d32cbcb5bfd3864db',
    messagingSenderId: '366984975682',
    projectId: 'notely-19368',
    storageBucket: 'notely-19368.appspot.com',
    iosClientId: '366984975682-jbu8hosk85sdn3qbd97sps09q1uuc1do.apps.googleusercontent.com',
    iosBundleId: 'com.example.notely',
  );
}
